import { TextWeight } from './typography-types.ts';

// Mapping weight number to font family name
export const weightToFontFamily: Record<TextWeight, string> = {
  300: 'Manrope-Light',
  400: 'Manrope-Regular',
  500: 'Manrope-Medium',
  600: 'Manrope-SemiBold',
  700: 'Manrope-Bold',
  800: 'Manrope-ExtraBold',
};

export const IconEnum = {
  Shield: '',
  Document: '',
  CardAdd: '',
  Check: '',
  Edit: '',
  Home: '',
  Info: '',
  Send: '',
  Settings: '',
  Share: '',
  Verified: '',
  AccountSecure: '',
  Archive: '',
  Hide: '',
  Password: '',
  Show: '',
  Sim: '',
  Wallet: '',
  More: '',
  Notification: '',
  Time: '',
  Graph: '',
  User: '',
  Dollar: '',
  SolarPassword: '',
  LockTime: '',
  Secured: '',
  Shop: '',
  Moon: '',
  Sun: '',
  FallOutline: '',
  SendOutline: '',
  HideOutline: '',
  MobileOutline: '',
  QrOutline: '',
  SwapOutline: '',
  HourglassOutline: '',
  QrScanOutline: '',
  SignalRodOutline: '',
  SignalOutline: '',
  DocumentOutline: '',
  ArrowLeftOutline: '',
  ArrowRightOutline: '',
  ChevronDownOutline: '',
  ChevronLeftOutline: '',
  ChevronRightOutline: '',
  ChevronUpOutline: '',
  ShareOutline: '',
  CardAddOutline: '',
  ReceivedOutline: '',
  CheckOutline: '',
  CloseOutline: '',
  ExchangeOutline: '',
  EditOutline: '',
  HomeOutline: '',
  InfoOutline: '',
  MixOutline: '',
  SearchOutline: '',
  SettingsOutline: '',
  VerifiedOutline: '',
  ArchiveOutline: '',
  ArrowDownOutline: '',
  ArrowUpOutline: '',
  CompanyOutline: '',
  DollarOutline: '',
  PasswordOutline: '',
  ShowOutline: '',
  SimOutline: '',
  NotificationOutline: '',
  TimeOutline: '',
  WalletOutline: '',
  FaceIdOutline: '',
  MoreOutline: '',
  UserOutline: '',
  GraphOutline: '',
  SolarPasswordOutline: '',
  ArrowGrowOutline: '',
  ShopOutline: '',
  ShieldOutline: '',
} as const;
export type IconEnum = (typeof IconEnum)[keyof typeof IconEnum];
