import { Insets, StyleSheet } from 'react-native';

export const UXTapZone: Insets = { right: 10, top: 10, left: 10, bottom: 10 };
export const layoutPadding = 16;
export const sharedLayoutStyles = StyleSheet.create({
  gap4: { gap: 4 },
  gap8: { gap: 8 },
  gap12: { gap: 12 },
  gap16: { gap: 16 },
  gap24: { gap: 24 },
  gap32: { gap: 32 },
  mt8: { marginTop: 8 },
  mt12: { marginTop: 12 },
  mt16: { marginTop: 16 },
  mt24: { marginTop: 24 },
  mt32: { marginTop: 32 },
  mb4: { marginBottom: 4 },
  mb8: { marginBottom: 8 },
  mb12: { marginBottom: 12 },
  mb16: { marginBottom: 16 },
  mb24: { marginBottom: 24 },
  mb32: { marginBottom: 32 },
  p4: { padding: 4 },
  p8: { padding: 8 },
  p12: { padding: 12 },
  p16: { padding: 16 },
  p24: { padding: 24 },
  p32: { padding: 32 },
  ph8: { paddingHorizontal: 8 },
  ph12: { paddingHorizontal: 12 },
  ph16: { paddingHorizontal: 16 },
  ph24: { paddingHorizontal: 24 },
  ph32: { paddingHorizontal: 32 },
  phLayout: {
    paddingHorizontal: layoutPadding,
  },
  m8: { margin: 8 },
  m12: { margin: 12 },
  m16: { margin: 16 },
  m24: { margin: 24 },
  m32: { margin: 32 },
  mh8: { marginHorizontal: 8 },
  mh12: { marginHorizontal: 12 },
  mh16: { marginHorizontal: 16 },
  mh24: { marginHorizontal: 24 },
  mh32: { marginHorizontal: 32 },
  mhLayout: {
    marginHorizontal: layoutPadding,
  },
  br8: { borderRadius: 8 },
  br12: { borderRadius: 12 },
  br16: { borderRadius: 16 },
  br24: { borderRadius: 24 },
  br32: { borderRadius: 32 },
  column: { flexDirection: 'column' },
  columnAlignCenter: { flexDirection: 'column', alignItems: 'center' },
  columnJustifyCenter: { flexDirection: 'column', justifyContent: 'center' },
  columnJustifyBetween: { flexDirection: 'column', justifyContent: 'space-between' },
  columnCenterBetween: { flexDirection: 'column', alignItems: 'center', justifyContent: 'space-between' },
  row: { flexDirection: 'row' },
  rowAlignCenter: { flexDirection: 'row', alignItems: 'center' },
  rowJustifyCenter: { flexDirection: 'row', justifyContent: 'center' },
  rowJustifyBetween: { flexDirection: 'row', justifyContent: 'space-between' },
  rowCenterBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  center: { alignItems: 'center', justifyContent: 'center' },
  fullWidth: {
    width: '100%',
  },
  fullHeight: {
    height: '100%',
  },
  fullLayout: {
    width: '100%',
    height: '100%',
  },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  flex3: { flex: 3 },
  flexGrow1: {
    flexGrow: 1,
  },
  flexWrap: { flexWrap: 'wrap' },
});
